application: doodle-man
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /res
  static_dir: res

- url: /scripts
  static_dir: scripts

- url: /levels
  static_dir: levels

- url: /animations
  static_dir: animations

- url: /data
  static_dir: data

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
