const name = "doodleman_v1";
const staticFiles = """staticFiles"""; // will be generated by server

self.addEventListener("install", async e => {
  let cache = await caches.open(name);
  await cache.addAll(staticFiles);
  return self.skipWaiting();
});

self.addEventListener("activate", async e => {
  self.clients.claim();
});

self.addEventListener("fetch", async e => {
  let r = e.request;
  let url = new URL(r.url);
  if (url.origin==location.origin) e.respondWith(cacheFirst(r));
  else e.respondWith(networkFirst(r));
});

async function cacheFirst(r) {
  let cache = await caches.open(name);
  let cached = await cache.match(r);
  return cached || fetch(r);
}
async function networkFirst(r) {
  let cache = await caches.open(name);
  try {
    let fresh = await fetch(r);
    await cache.put(r,fresh.clone());
    return fresh;
  }
  catch(e) {
    let cached = await cache.match(r);
    return cached
  }
}
